import Header from "@/components/header/header";
import type { Metadata } from "next";
import "./globals.scss";
import { Lato } from 'next/font/google';

import Footer from "@/components/footer/Footer";
import Providers from "@/utils/providers";

const roboto = Lato({
  weight: ['400', '700'],
  subsets: ['latin'],
  style: ['normal'],
  display: 'swap',
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={roboto.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
