import Header from "@/components/header/header";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.scss";

import Footer from "@/components/footer/Footer";
import Providers from "@/utils/providers";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body className={inter.className}>
        <Providers>
            <Header/>
            {children}
            <Footer/>
        </Providers>
        </body>
        </html>
    );
}
